version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123"
    ports:
        - 5432:5432
    volumes:
        - ./postgres-data:/var/lib/postgresql/data

  elasticsearch:
    image: elasticsearch:7.12.0
    ports:
      - "9200:9200" #http
      - "9300:9300" #tcp
    environment:
      - discovery.type=single-node
  